name: CD
on:
  push:
    tags:
      - "**"
jobs:
  publish-docker-image:
    name: Publish Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: ikmu/conote
          tags: |
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
  
  publish-helm-chart:
    name: Publish Helm chart
    runs-on: ubuntu-latest
    needs: publish-docker-image

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install helm
        uses: azure/setup-helm@v1
      - name: Update helm chart dependency
        run: helm dependency update deploy/charts/conote
      - name: Package helm chart
        run: helm package deploy/charts/conote
      - name: Login to helm registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io --username ${{ github.actor }} --password-stdin
      - name: Push helm chart
        run: |
          helm push $(find conote-*.tgz) oci://ghcr.io/kmu-dev/helm
  
  sentry-release:
    name: Sentry release
    runs-on: ubuntu-latest
    needs: publish-helm-chart
    defaults:
      run:
        working-directory: api

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          cache-dependency-path: api/yarn.lock
      - name: Install dependencies
        run: yarn install
      - name: Generate prisma client
        run: yarn prisma generate
      - name: Build
        run: yarn build
      - name: Generate Sentry release version
        id: generate-version
        uses: actions/github-script@v6
        env:
          VERSION: ${{ github.ref_name }}
        with:
          result-encoding: string
          script: |
            const { VERSION } = process.env;
            return VERSION.startsWith('v') ? VERSION.substring(1) : VERSION;
      - name: Create sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          version: ${{ steps.generate-version.outputs.result }}
          sourcemaps: './api/dist'