name: Publish helm chart
on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install helm
        uses: azure/setup-helm@v1
      - name: Update helm chart dependency
        run: helm dependency update deploy/charts/conote
      - name: Package helm chart
        run: helm package deploy/charts/conote
      - name: Login to helm registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io --username ${{ github.actor }} --password-stdin
      - name: Push helm chart
        run: |
          for file in *.tgz; do mv $file ${file//conote/conote-helm}; done
          helm push $(find conote-helm-*.tgz) oci://ghcr.io/kmu-dev
